import { ref, computed } from 'vue';

const locale = ref(localStorage.getItem('ssc_locale') || 'en');

const translations = {
    en: {
        // Navigation / General
        'our_story': 'About Us',
        'philosophy': 'Our Cooking',
        'policies': 'Booking Policies',
        'dashboard': 'Dashboard',
        'sign_in': 'Sign In',
        'register': 'Register',
        'logout': 'Log Out',
        'packages': 'Packages',
        'orders': 'Bookings',
        'profile': 'My Profile',
        'menu': 'Menu',
        'all_packages': 'All Packages',
        'wedding_packages': 'Wedding Packages',
        'corporate_packages': 'Corporate Packages',
        'aqiqah_family': 'Aqiqah & Family',
        'search_placeholder': 'Search for a package...',
        'menu_highlights': 'Menu Highlights',
        'popular_tag': 'Most Popular',
        'value_tag': 'Value Choice',
        'premium_tag': 'Premium Quality',
        'signature_tag': 'Exclusive Signature',

        // Welcome / Public landing page
        'hero_subtitle': 'Tasty & Reliable Catering in Gong Badak',
        'hero_title_1': 'Traditional Flavors',
        'hero_title_2': 'Artfully Presented',
        'hero_title_3': 'For Unforgettable Moments',
        'hero_desc': 'Make your wedding, corporate event, or family gathering extra special with authentic Terengganu dishes. We serve delicious, traditional recipes cooked with love, and handle everything so you don\'t have to worry about a thing.',
        'begin_experience': 'Choose Package',
        'read_story': 'About Us',
        'service_standard': 'OUR PROMISE',
        'service_standard_desc': 'Always on time, clean and delicious food, and ready to help make your event a success.',
        'story_title_1': '01 / Fresh & Safe',
        'story_header_1': 'Fresh Ingredients & Tasty Meals',
        'story_desc_1': 'We source fresh ingredients from local Terengganu markets and cook them in a clean, hygienic kitchen. Every dish is prepared with care to make sure it is safe and tasty for your guests.',
        'story_title_2': '02 / Quick & Easy',
        'story_header_2': 'Plan According to Your Budget',
        'story_desc_2': 'Try our easy-to-use Budget Planner to plan your menu. Just enter your guest count or budget, and it will suggest the best package that fits your wallet perfectly.',
        'philosophy_tag': 'HOW WE COOK',
        'philosophy_title_1': 'Keeping Traditional Recipes',
        'philosophy_title_2': 'Authentic Terengganu Cooking',
        'philosophy_desc_1': 'We believe traditional food should taste good and look amazing. By cooking authentic Terengganu recipes passed down through generations and serving them beautifully, we make sure your guests enjoy every single bite.',
        'philosophy_desc_2': 'We deliver all food in warm thermal containers so everything stays hot, fresh, and delicious until it is served at your event.',
        'browse_packages': 'Choose Catering Package',
        'booking_policies': 'Booking Terms & Conditions',
        'policy_title_1': '01 / DEPOSIT',
        'policy_header_1': '30% Booking Deposit',
        'policy_desc_1': 'We need a 30% deposit to secure your event date. Since we use this deposit to buy fresh ingredients ahead of time, it cannot be refunded if you decide to cancel.',
        'policy_title_2': '02 / CANCELLATION',
        'policy_header_2': '7 Days Cancellation Notice',
        'policy_desc_2': 'If you need to cancel or change the number of guests, please let us know at least 7 days before the event. Any late changes might mean we cannot refund your deposit.',
        'policy_title_3': '03 / SANITATION',
        'policy_header_3': 'Guaranteed Cleanliness & Halal',
        'policy_desc_3': 'All our food is 100% Halal and prepared in a clean environment. We pack everything in clean, sealed thermal boxes to keep it safe and warm.',
        'copyright': 'SmartServe Catering Gong Badak. All rights reserved.',

        // Customer Dashboard
        'welcome_back': 'Welcome back',
        'welcome_desc': 'Let\'s work together to make your next event successful with delicious food and smooth service.',
        'email_verified_success': 'Email verified successfully! Welcome to your dashboard.',
        'order_now': 'Order Now',
        'shopping_cart': 'Cart',
        'total_bookings': 'Total Bookings',
        'quick_actions': 'Quick Actions',
        'our_menu': 'Catering Packages',
        'our_menu_desc': 'Browse and customize our packages for your event.',
        'browse_menu': 'Browse Packages',
        'budget_planner': 'Budget Planner',
        'budget_planner_desc': 'Tell us your budget, and we will recommend the best package for you instantly.',
        'open_planner': 'Open Budget Planner',
        'my_orders': 'My Orders',
        'my_orders_desc': 'Check your order status, deposit payments, and event details here.',
        'track_orders': 'Track Orders',
        'edit_profile': 'Edit Profile',
        'edit_profile_desc': 'Update your phone number, email, and delivery address anytime.',
        'settings': 'Settings',

        // Menu Index / Catalog
        'catering_packages': 'Catering Packages',
        'premium_selection': 'PREMIUM SELECTION',
        'select_occasion': 'Select Your Occasion',
        'starting_from': 'Starting from',
        'view_packages': 'View Packages',
        'no_packages_available': 'No catering packages available.',
        'contact_admin_menu': 'Oops! It looks like there are no packages here yet. Please contact us to get a custom quote.',

        // Menu Show / Details
        'pax': 'pax',
        'included_dishes': 'Included Dishes',
        'min_requirement': 'Minimum Requirement',
        'select_quantity': 'Select Guest Count (Pax)',
        'live_total': 'Live Total',
        'customize_order': 'Customize & Order',
        'direct_add_cart': 'Direct Add to Cart',
        'no_packages_found_cat': 'No packages found in this category.',
        'back_to_menu': 'Back to Menu',
        'scale_small': 'Intimate & Small Gathering',
        'scale_medium': 'Medium Gathering (Grand)',
        'scale_large': 'Mega Gathering (Mega Feast)',
        'category_show_desc': 'View available packages, estimate your guest count, and customize your catering order.',
        'cart_desc_banner': 'Review your selected catering packages, adjust your guest count, and proceed to complete your booking securely.',

        // Customizer
        'select_guest_count': 'Select Guest Count (Pax)',
        'min_booking_requirement_is': 'Minimum booking requirement is',
        'customize_extra_items': 'Customize Extra Items',
        'addons_desc': 'Select additional items to add to your catering set. Prices listed are per pax.',
        'price_breakdown': 'Price Breakdown',
        'base_pkg_price': 'Base Package Price',
        'guest_count': 'Guest Count',
        'addon_extra': 'Extra Add-on Items',
        'combined_cost_pax': 'Combined Cost Per Pax',
        'grand_total': 'Grand Total',
        'deposit_required': 'Deposit Required (30%)',
        'balance_due': 'Balance Due (70%)',
        'selected_extra_items': 'Selected Extra Items',
        'add_to_cart': 'Add to Cart',
        'cancel': 'Cancel',

        // Shopping Cart
        'package': 'Package',
        'price': 'Price',
        'quantity': 'Quantity',
        'subtotal': 'Subtotal',
        'action': 'Action',
        'order_summary': 'Order Summary',
        'selected_packages': 'Selected Packages',
        'proceed_checkout': 'Go to Checkout',
        'continue_shopping': 'Continue Shopping',
        'cart_empty': 'Your cart is empty',
        'cart_empty_desc': 'Looks like your cart is empty! Check out our packages to start planning.',
        'browse_packages_btn': 'Browse Packages',

        // Checkout
        'secure_checkout': 'Complete Your Booking',
        'event_delivery_details': 'Event & Delivery Details',
        'customer_name': 'Customer Name',
        'phone_number': 'Phone Number',
        'delivery_event_date': 'Event Date',
        'preferred_delivery_time': 'Delivery Time',
        'event_venue_address': 'Venue Address',
        'payment_slip_deposit': 'Upload Deposit Receipt (30%)',
        'deposit_commitment_desc': 'Please scan the QR code or transfer the 30% deposit to our account. Once done, upload your receipt here so we can confirm and lock in your event date.',
        'scan_to_pay': 'Scan to Pay',
        'qr_not_configured': 'QR Not Configured',
        'upload_payment_slip': 'Upload Payment Receipt',
        'select_receipt_file': 'Choose Receipt File',
        'accepted_formats_desc': 'JPEG, PNG, PDF (Max 4MB)',
        'confirm_booking_submit': 'Confirm & Submit Booking',
        'customer_notes': 'Customer Notes / Special Requests',
        'customer_notes_placeholder': 'E.g., food allergies, setup preferences, location directions...',
        'delivery_tab': 'Delivery',
        'view_available_promos': 'View Available Promo Codes',
        'available_promo_codes': 'Available Promo Codes',
        'no_active_promos': 'No active promo codes at this moment.',
        'use_promo_code': 'Apply Code',
        'min_spend_label': 'Min Spend',
        'expires_label': 'Valid until',
        'pickup_time': 'Pickup Time',
        'click_to_enlarge': 'Click to enlarge',

        // Bookings / Orders
        'my_bookings': 'My Bookings',
        'all': 'All',
        'pending_rejected': 'Pending/Rejected',
        'confirmed': 'Confirmed',
        'delivered_tab': 'Delivered',
        'awaiting_verification': 'Checking Receipt',
        'completed_tab': 'Completed',
        'cancelled_tab': 'Cancelled',
        'order_id': 'Order ID',
        'delivery_event_date_label': 'Event Date',
        'total_price': 'Total Price',
        'status_label': 'Status',
        'order_timeline_tracker': 'Order Status Tracker',
        'timeline_submitted': 'Submitted',
        'timeline_confirmed': 'Confirmed (30%)',
        'timeline_delivered': 'Delivered',
        'timeline_completed': 'Completed (100%)',
        'rejection_reason_admin': 'Reason for Rejection:',
        'view_invoice': 'View Invoice',
        'reupload_receipt_btn': 'Re-upload Receipt',
        'cancel_event_btn': 'Cancel Booking',
        'no_bookings_found': 'No bookings found',
        'no_bookings_found_desc': 'You don\'t have any bookings in this section yet.',
        'pending': 'Pending',
        'deposit_rejected': 'Deposit Rejected',
        'balance_rejected': 'Balance Rejected',
        'confirm_cancel_order': 'Are you sure you want to cancel this order? Please note that deposits are non-refundable.',
        'confirm_remove_cart': 'Are you sure you want to remove this package from your cart?',
        'confirm_action': 'Confirm Action',
        'yes_confirm': 'Yes, Confirm',
        'no_cancel': 'No, Cancel',
        'toast_order_cancelled': 'Your booking has been cancelled.',
        'checkout_desc_banner': 'Confirm your event details, upload your deposit receipt (30%), and submit your booking for our team to review.',
        'file_size_error': 'File size must be less than 4MB.',
        'toast_receipt_uploaded': 'Receipt uploaded successfully!',
        'toast_added_to_cart': 'Package added to cart successfully!',
        'toast_order_submitted': 'Your booking request has been submitted successfully.',
        'toast_item_removed': 'Item removed from shopping cart.',
        'toast_qty_updated': 'Quantity updated successfully.',
        'toast_cart_updated': 'Cart item updated successfully!',
        'uploading': 'Uploading...',

        // Invoice receipt Show
        'invoice_receipt': 'Invoice & Receipt',
        'print_invoice': 'Print Invoice',
        'back_to_bookings': 'Back to Bookings',
        'billed_to': 'Billed To',
        'event_schedule_venue': 'Event Details & Venue:',
        'itemized_breakdown': 'Order Details',
        'catering_service_package': 'Catering Service Package',
        'price_pax': 'Price / pax',
        'guest_qty': 'Guests',
        'payment_trans_status': 'Payment Status',
        'deposit_paid_invoice': 'Deposit Paid (30%)',
        'remaining_balance_invoice': 'Remaining Balance (70%)',
        'thank_you_footer': 'Thank you for choosing SmartServe Catering. We are excited to make your event wonderful!',
        'issued': 'Issued',
        'email': 'Email',
        'phone': 'Phone',
        'setup_time': 'Setup Time',
        'venue_address': 'Venue Address',
        'base_cost': 'Base Cost',
        'payment_desc_invoice': 'We have received your 30% deposit. The remaining 70% balance can be paid on or before the day of your event.',

        // Dashboard Tracker & Recent Bookings
        'active_order_tracker': 'Active Order Status',
        'no_active_order': 'You don\'t have any active orders right now. Want to book one?',
        'recent_bookings': 'Recent Bookings',
        'package_name': 'Package',
        'event_date': 'Event Date',
        'pax_count': 'Guests',
        'grand_total_label': 'Grand Total',
        'view_details': 'View Details',
        'no_recent_bookings': 'No bookings found.',
        'order_num': 'Order',
        'action_required': 'Action Required',
        'reupload_rejected_slip': 'Please upload a clear copy of your payment receipt so we can verify it.',
        'timeline_step_1': 'Placed',
        'timeline_step_2': 'Confirmed',
        'timeline_step_3': 'Delivered',
        'timeline_step_4': 'Completed',

        // Dynamic Dashboard
        'upcoming_event': 'Your Upcoming Event',
        'days_remaining': 'Days Remaining',
        'day_remaining': 'Day Remaining',
        'event_today': 'Event is Today!',
        'event_completed_days': 'Event occurred',
        'financial_summary': 'Payment Summary',
        'deposit_paid': 'Deposit Paid (30%)',
        'balance_due_payment': 'Balance Due (70%)',
        'upload_balance_receipt': 'Upload Balance Receipt (70%)',
        'balance_submitted_verification': 'Balance receipt uploaded. We are verifying it now.',
        'featured_packages_title': 'Packages For You',
        'featured_packages_subtitle': 'Specially curated packages for your special events.',
        'catering_guidelines': 'Event Planning Tips',
        'guide_pax_title': 'How many guests should I order for?',
        'guide_pax_desc': 'It is always safe to order for 10% more than your guest list just in case. Note that our packages have a minimum requirement (like 50 or 100 guests).',
        'guide_halal_title': 'Halal & Food Safety',
        'guide_halal_desc': 'Our team cooks in a clean, hygienic kitchen. All meals are delivered in sealed thermal boxes to make sure they arrive hot and fresh.',
        'guide_changes_title': 'Making changes to your menu',
        'guide_changes_desc': 'Please finalize your guest count and menu changes at least 7 days before the event so we can prepare the ingredients.',

        // Budget Planner
        'calc_by_budget': 'Search by Budget',
        'calc_by_guest': 'Search by Guest Count',
        'enter_target_budget': 'Enter Your Budget (RM)',
        'enter_guest_count': 'Enter Number of Guests',
        'calculate_btn': 'Find Packages',
        'recommendations': 'Packages For You',
        'select_customize_btn': 'Choose & Customize',
        'leftover_budget': 'Remaining Budget',
        'pax_recommended': 'Recommended Guest Count',
        'no_results_found': 'No packages match your search.',
        'no_results_desc': 'Try increasing your budget or reducing the number of guests.',
        'step_planning_mode': 'Step 1: Choose Planning Method',
        'step_base_package': 'Step 2: Choose Your Package',
        'step_addons': 'Step 3: Add Extra Items (Optional)',
        'live_estimate': 'Estimated Total Price',
        'book_customize_plan': 'Book & Customize',
        'budget_exceeded': 'Over Budget By',
        'within_budget': 'Within Budget!',
        'insufficient_budget': 'Budget is too low for this package.',
        'insufficient_budget_desc': 'Your budget is below the minimum guest requirement for this package. Try adjusting your budget or guests.',
        'auto_adjusted_min': 'Automatically set to minimum package requirement.',
        'reviews_ratings': 'Reviews & Ratings',
        'write_review': 'Write a Review',
        'review_rating': 'Rating',
        'review_comment': 'Your Review',
        'review_comment_placeholder': 'Tell us what you think about our food and service...',
        'submit_review': 'Submit Review',
        'admin_reply_label': 'Reply from Owner',
        'no_reviews_yet': 'No reviews yet.',
        'review_success': 'Thank you! Your review has been submitted.',
        'review_stars': 'Stars',
        'overall_rating': 'Overall Rating',
        'customer_testimonials': 'What Our Customers Say',
        'promo_code': 'Promo Code',
        'apply_promo_btn': 'Use Code',
        'promo_applied': 'Promo Code Applied',
        'discount': 'Discount',
        'fully_booked_date': 'Fully Booked / Unavailable Date',

        // New Landing Page Translations
        'our_packages': 'Packages',
        'faq': 'FAQ',
        'contact_us': 'Contact Us',
        'about_subtitle': 'ESTABLISHED IN GONG BADAK',
        'about_title_1': 'Delicious Cooking',
        'about_title_2': 'For Your Special Events',
        'about_desc_1': 'SmartServe Catering started with a simple goal: to serve delicious, traditional East Coast dishes at modern events. We blend authentic recipes with elegant setups and reliable service.',
        'about_desc_2': 'Whether it is a small family gathering, a beautiful wedding, or a corporate event, we handle all the food and setup so you can relax and enjoy the day.',
        'stats_events': 'Events Catered',
        'stats_guests': 'Guests Served',
        'stats_halal': 'Halal Assurance',
        'stats_recipes': 'Signature Dishes',
        'stats_halal_val': '100% Halal',
        'values_title': 'Our Promises',
        'value_1_title': 'Traditional Taste',
        'value_1_desc': 'We cook authentic Terengganu dishes using fresh ingredients from local markets.',
        'value_2_title': 'Good Value',
        'value_2_desc': 'We organize everything carefully to give you the best food and service within your budget.',
        'value_3_title': 'Clean & Beautiful',
        'value_3_desc': 'We set up our buffet and tables beautifully to make your event look extra special.',
        'packages_title': 'Our Packages',
        'packages_subtitle': 'Browse through our packages. Click "Customize" to change the dishes or adjust the guest count as you like!',
        'customize_this_package': 'Customize Package',
        'faq_title': 'Common Questions',
        'faq_subtitle': 'Have questions? Here are the answers to things our customers ask us most often.',
        'faq_q1': 'Is the food completely Halal?',
        'faq_a1': 'Yes, absolutely! All our ingredients are sourced from Halal suppliers and we cook in a clean, hygienic kitchen.',
        'faq_q2': 'When do I need to finalize the guest count?',
        'faq_a2': 'Please confirm your final guest count and menu choices at least 7 days before the event. This helps us buy the fresh ingredients and prepare on time.',
        'faq_q3': 'Do you deliver outside of Kuala Terengganu?',
        'faq_a3': 'We mostly cater around Kuala Terengganu, Kuala Nerus, Gong Badak, and Marang. If your event is outside these areas, just contact us to discuss transport arrangements.',
        'faq_q4': 'How is food freshness maintained during delivery?',
        'faq_a4': 'We deliver food in sealed thermal container boxes so everything stays hot and fresh until your event starts.',
        'faq_q5': 'Can I change the base dishes in a package?',
        'faq_a5': 'Yes! You can swap any base dish in the package with other choices in the same category for free, or add extra side dishes as you like.',
        'contact_title': 'Contact Us',
        'contact_subtitle': 'Have questions or need a custom menu? Send us a message below or chat with us on WhatsApp!',
        'contact_name': 'Your Name',
        'contact_email': 'Email Address',
        'contact_phone': 'Phone Number',
        'contact_date': 'Event Date',
        'contact_pax': 'Number of Guests',
        'contact_type': 'Event Type',
        'contact_message': 'Your Message',
        'contact_submit': 'Submit',
        'contact_whatsapp_btn': 'Chat on WhatsApp',
        'contact_type_wedding': 'Wedding / Reception',
        'contact_type_corporate': 'Corporate Event',
        'contact_type_social': 'Private Gathering / Party',
        'contact_type_other': 'Other Occasions',
        'inquiry_success': 'Your message has been sent successfully. We will get back to you soon!',
        'inquiry_whatsapp_text': 'Hi SmartServe Catering! I would like to inquire about a catering package. Here are my details:\nName: {name}\nEvent Date: {date}\nGuests: {pax} pax\nEvent Type: {type}\nMessage: {message}',
        // Additions for landing pages
        'booking_policies_title': 'Booking Policies',
        'booking_policies_subtitle': 'Please read our policies before placing your order.',
        'policy_header_3': 'Menu Changes',
        'policy_desc_3': 'You can change your menu up to 7 days before the event. Any last-minute changes depend on ingredient availability and may incur extra costs.',
        'policy_header_4': 'Guest Count',
        'policy_desc_4': 'Please confirm your final guest count 3 days before the event. If you need to add more guests last minute, extra charges will apply.',
        'policy_header_5': 'Halal Guarantee',
        'policy_desc_5': 'All our food is 100% Halal. We buy fresh ingredients from trusted suppliers and keep our kitchen very clean.',
        'policy_header_6': 'Feedback & Complaints',
        'policy_desc_6': 'If you have any feedback or complaints, please let us know within 24 hours after the event so we can make things right.',
        'agreement_banner_title': 'Booking Agreement',
        'agreement_banner_desc': 'Once you pay the deposit, it means you agree to our booking terms and conditions. We look forward to serving you!',
        'ask_us': 'Ask Us',
        'view_all_questions': 'View All Questions',
        'q_min_guests': 'What is the minimum guest requirement?',
        'q_halal': 'Are the meals certified Halal?',
        'q_menu_change': 'Can I change the menu dishes?',
        'q_payment': 'What payment methods do you accept?',
        'about_quote': '"We treat every event like our own family gathering, serving only the best."',
        'achievements_title': 'Our Achievements',
        'milestones_title': 'Our Journey',
        'milestones_subtitle': 'Growing from Gong Badak to all of Terengganu',
        'journey_2009_title': 'Small Beginnings',
        'journey_2009_desc': 'We started small in Gong Badak, cooking traditional food for village weddings and family gatherings.',
        'journey_2015_title': 'Serving More Customers',
        'journey_2015_desc': 'We expanded to Kuala Terengganu and Nerus, helping to feed over 1,000 guests at large weddings.',
        'journey_2020_title': 'Going Online',
        'journey_2020_desc': 'We built this online platform to help you plan, customize menus, and book directly from home.',
        'journey_now_title': 'Where We Are Today',
        'journey_now_desc': 'With over 500 successful events, we are proud to be one of the most trusted catering services in Terengganu.',
        'ready_dream_event': 'Ready to plan your event?',
        'ready_dream_desc': 'Get in touch with us today to discuss the best menu options for your guests.',
        'start_journey_title': 'Get Started',
        'connect_coordinates': 'Get in Touch',
        'address_label': 'Our Address',
        'hotline_label': 'Call Us',
        'email_label': 'Email',
        'whatsapp_click_desc': 'Chat with us on WhatsApp',
        'service_area_desc': 'We cater for events in Kuala Terengganu, Kuala Nerus, Gong Badak, Marang, and nearby areas.',
        'business_hours_title': 'Business Hours',
        'weekday_label': 'Monday – Friday',
        'saturday_label': 'Saturday',
        'sunday_label': 'Sunday',
        'booking_only_label': 'Bookings only',
        'contact_reply_notice': 'We will reply to you within 24 hours!',
        'faq_q1_text': 'What is the minimum number of guests for booking?',
        'faq_a1_text': 'For most packages, the minimum is 100 guests. For weddings, it is 500 guests. If you have fewer guests, feel free to contact us to discuss!',
        'faq_q2_text': 'How long does the booking and confirmation process take?',
        'faq_a2_text': 'We confirm bookings in 1-2 working days. Once your deposit is paid, we will contact you to finalize the menu and schedule.',
        'faq_q3_text': 'Do you offer services outside Terengganu?',
        'faq_a3_text': 'We cover Kuala Terengganu, Kuala Nerus, Gong Badak, and Marang. If your event is outside these areas, reach out to us and we will see how we can help.',
        'faq_q4_text': 'Can the menu be customized for special dietary needs?',
        'faq_a4_text': 'Yes, you can swap dishes in your menu! Just let us know any changes at least 7 days before. We also cater to vegetarians and food allergies.',
        'faq_q5_text': 'What payment methods do you accept?',
        'faq_a5_text': 'You can pay via bank transfer (FPX), cash, or e-wallet. We require a 30% deposit to lock the date, and the remaining 70% is due 3 days before the event.',
        'faq_q6_text': 'Are your meals certified Halal?',
        'faq_a6_text': 'Yes, 100% Halal. We buy all our ingredients from Halal suppliers certified by JAKIM.',
        'faq_q7_text': 'What is included in the basic package?',
        'faq_a7_text': 'Our basic packages include the food, plates/cups/cutlery, buffet tables, and servers. If you need tents, tables, or chairs, you can add them as extras.',
        'faq_q8_text': 'What happens if I need to cancel my booking?',
        'faq_a8_text': 'Cancel more than 30 days before: get 100% refund. 14-30 days before: get 50% refund. Less than 14 days before: deposit cannot be refunded.',
        // Packages Page Keys
        'packages_hero_title_1': 'Our Catering',
        'packages_hero_title_2': 'Packages',
        'packages_hero_desc': 'Choose the perfect package for your event. You can customize the menu and guest count to fit your needs.',
        'min_booking': 'Min. Booking',
        'select_package': 'Select Package',
        'special_package': 'Special Package',
        'want_something_special': 'Want Something More Special?',
        'custom_menu_desc': 'We can also create a custom menu just for you, matching your theme, budget, and special requests.',
        'mock_pkg_1_name': 'Wedding Silver',
        'mock_pkg_1_desc': 'Classic wedding package featuring aromatic rice, chicken, beef kerutuk, and delicious local desserts.',
        'mock_pkg_2_name': 'Corporate Bronze',
        'mock_pkg_2_desc': 'Great for office events. Comes with fusion recipes, hot drinks, pastries, and popular local food.',
        'mock_pkg_3_name': 'Aqiqah & Gathering',
        'mock_pkg_3_desc': 'Traditional feast featuring lamb curry, signature dalca, aromatic ghee rice, and local side dishes.',
        // FrontLayout Navbar & Footer
        'home_nav': 'Home',
        'about_nav': 'About',
        'package_nav': 'Packages',
        'faq_nav': 'FAQ',
        'contact_nav': 'Contact',
        'explore_title': 'Explore',
        'connect_title': 'Contact',
        'footer_desc': 'Serving tasty, traditional Terengganu food with beautiful setups for all your special events.',
        // FrontLayout Auth Drawers
        'reset_password': 'Reset Password',
        'set_new_password': 'Set New Password',
        'email_address_label': 'Email Address',
        'password_label': 'Password',
        'forgot_password_btn': 'Forgot Password?',
        'remember_session': 'Keep me logged in',
        'signing_in_status': 'Signing In...',
        'no_account_notice': 'Don\'t have an account?',
        'your_name_label': 'Your Name',
        'full_name_label': 'Full Name',
        'phone_number_label': 'Phone Number',
        'delivery_address_label': 'Home / Venue Address',
        'confirm_password_label': 'Confirm Password',
        'registering_status': 'Registering...',
        'already_registered_notice': 'Already have an account?',
        'forgot_password_desc': 'Forgot your password? No worries. Just enter your email below and we will send you a link to set a new one.',
        'send_reset_link_btn': 'Email Reset Link',
        'sending_status': 'Sending...',
        'back_to_btn': 'Back to',
        'current_password': 'Current Password',
        'new_password_label': 'New Password',
        'confirm_new_password_label': 'Confirm New Password',
        'resetting_status': 'Resetting...',
        'read_more': 'Read More',
        'view_all_packages': 'View All Packages',
        'testimonials_subtitle': 'Read what our customers say about our food and service.',
        'years_serving': 'Years of Experience',
        'milestones_tag': 'Our Journey',
        'faq_title_1': 'Commonly',
        'faq_title_2': 'Asked',
        'faq_title_3': 'Questions',
        'faq_subtitle_desc': 'Here are the answers to questions we get asked most often about bookings and food.',
        'still_have_questions': 'Still Have Questions?',
        'still_have_questions_desc': 'Just reach out to us directly! We are happy to help you with any questions.',
        'error_name_required': 'Name is required.',
        'error_email_required': 'Email is required.',
        'error_email_invalid': 'Email is invalid.',
        'error_phone_required': 'Phone number is required.',
        'error_date_required': 'Event date is required.',
        'error_pax_required': 'Guest count is required.',
        'error_message_required': 'Message is required.',
        'placeholder_name': 'Your name',
        'placeholder_email': 'email@example.com',
        'placeholder_phone': '+60 12-345 6789',
        'placeholder_pax': 'E.g., 500',
        'placeholder_message': 'Tell us more about your event...',
        'values_desc': 'We follow these guidelines to make sure your food is safe, clean, and delicious.',
        'now_label': 'Now',
        'profile_information': 'Profile Information',
        'profile_info_desc': 'Update your account\'s profile information and email address.',
        'update_password': 'Update Password',
        'update_password_desc': 'Ensure your account is using a long, random password to stay secure.',
        'delete_account': 'Delete Account',
        'delete_account_desc': 'Once your account is deleted, all of its resources and data will be permanently deleted. Before deleting your account, please download any data or information that you wish to retain.',
        'delete_confirm_title': 'Are you sure you want to delete your account?',
        'delete_confirm_desc': 'Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.',
        'personal_account': 'Personal Account',
        'save_changes': 'Save Changes',
        'session_expired_title': 'Session Expired',
        'session_expired_desc': 'Your session has expired due to inactivity. Please log in again to continue.'
    },
    my: {
        // Navigation / General
        'our_story': 'Tentang Kami',
        'philosophy': 'Cara Memasak',
        'policies': 'Polisi Tempahan',
        'dashboard': 'Dashboard',
        'sign_in': 'Log Masuk',
        'register': 'Daftar',
        'logout': 'Log Keluar',
        'packages': 'Pakej',
        'orders': 'Tempahan Saya',
        'profile': 'Profil Saya',
        'menu': 'Menu',
        'all_packages': 'Semua Pakej',
        'wedding_packages': 'Pakej Kahwin',
        'corporate_packages': 'Pakej Korporat',
        'aqiqah_family': 'Aqiqah & Kenduri',
        'search_placeholder': 'Cari pakej katering...',
        'menu_highlights': 'Menu Pilihan',
        'popular_tag': 'Paling Laris',
        'value_tag': 'Sangat Berbaloi',
        'premium_tag': 'Kualiti Premium',
        'signature_tag': 'Menu Istimewa',

        // Welcome / Public landing page
        'hero_subtitle': 'Katering Sedap & Dipercayai di Gong Badak',
        'hero_title_1': 'Lauk Tradisional',
        'hero_title_2': 'Hidangan Kemas',
        'hero_title_3': 'Untuk Majlis Istimewa Anda',
        'hero_desc': 'Jom buat majlis perkahwinan, kenduri, aqiqah, atau acara korporat anda lebih meriah dengan lauk-pauk Pantai Timur yang sedap. Kami masak menggunakan rempah-ratus asli Terengganu dan uruskan semuanya untuk anda.',
        'begin_experience': 'Pilih Pakej',
        'read_story': 'Tentang Kami',
        'service_standard': 'JANJI KAMI',
        'service_standard_desc': 'Makanan sampai tepat pada masa, dijamin bersih dan sedap, serta sedia membantu majlis anda berjalan lancar.',
        'story_title_1': '01 / Bersih & Lazat',
        'story_header_1': 'Bahan Segar dari Pasar',
        'story_desc_1': 'Kami hanya guna bahan mentah yang segar dan halal dari pasar tempatan. Dapur kami sentiasa bersih untuk memastikan setiap hidangan selamat dan sedap dinikmati.',
        'story_title_2': '02 / Mudah & Cepat',
        'story_header_2': 'Rancang Ikut Poket Anda',
        'story_desc_2': 'Guna Perancang Bajet kami untuk kira kos katering mengikut bajet anda. Masukkan jumlah tetamu atau had bajet, sistem akan cadangkan pakej terbaik secara automatik.',
        'philosophy_tag': 'CARA KAMI MEMASAK',
        'philosophy_title_1': 'Kekalkan Rasa Asli',
        'philosophy_title_2': 'Lauk Warisan Terengganu',
        'philosophy_desc_1': 'Kami kekalkan rasa masakan asli Terengganu. Dimasak dengan rempah-ratus warisan turun-temurun, setiap lauk pastinya menyelerakan dan memuaskan hati semua tetamu anda.',
        'philosophy_desc_2': 'Semua lauk dihantar menggunakan bekas terma khas supaya makanan kekal panas, segar, dan sedap apabila dihidangkan nanti.',
        'browse_packages': 'Pilih Pakej Katering',
        'booking_policies': 'Terma & Syarat Tempahan',
        'policy_title_1': '01 / DEPOSIT',
        'policy_header_1': 'Deposit Tempahan 30%',
        'policy_desc_1': 'Deposit 30% diperlukan untuk lock tarikh majlis anda. Minta maaf ya, deposit ini tidak boleh dikembalikan kalau batal sebab kami dah mula buat persiapan dan beli bahan masakan.',
        'policy_title_2': '02 / PEMBATALAN',
        'policy_header_2': 'Batal 7 Hari Sebelum',
        'policy_desc_2': 'Kalau nak batal majlis atau tukar bilangan tetamu, tolong maklumkan sekurang-kurangnya 7 hari sebelum tarikh majlis ya. Makluman saat-saat akhir boleh menyebabkan deposit hangus.',
        'policy_title_3': '03 / KEBERSIHAN',
        'policy_header_3': 'Jaminan Halal & Kebersihan',
        'policy_desc_3': 'Semua hidangan kami 100% Halal. Lauk-pauk dimasak bersih dan disimpan dalam bekas terma tertutup rapat supaya kekal panas dan selamat dimakan.',
        'copyright': 'SmartServe Catering Gong Badak. Hak cipta terpelihara.',

        // Customer Dashboard
        'welcome_back': 'Selamat kembali',
        'welcome_desc': 'Jom bekerjasama untuk pastikan majlis anda berjalan lancar dengan makanan yang sedap dan servis yang memuaskan.',
        'order_now': 'Tempah Sekarang',
        'shopping_cart': 'Troli',
        'total_bookings': 'Jumlah Tempahan',
        'quick_actions': 'Tindakan Pantas',
        'our_menu': 'Pakej Katering',
        'our_menu_desc': 'Lihat dan ubah suai pakej tradisional untuk majlis anda.',
        'browse_menu': 'Lihat Pakej',
        'budget_planner': 'Perancang Bajet',
        'budget_planner_desc': 'Masukkan bajet anda dan dapatkan cadangan pakej katering yang sesuai dengan poket anda serta-merta.',
        'open_planner': 'Buka Perancang Bajet',
        'my_orders': 'Tempahan Saya',
        'my_orders_desc': 'Semak status tempahan, bayaran deposit, dan jadual majlis anda di sini.',
        'track_orders': 'Jejak Tempahan',
        'edit_profile': 'Edit Profil',
        'edit_profile_desc': 'Kemas kini nombor telefon, e-mel dan alamat penghantaran anda di sini.',
        'settings': 'Tetapan',

        // Menu Index / Catalog
        'catering_packages': 'Pakej Katering',
        'premium_selection': 'PILIHAN PREMIUM',
        'select_occasion': 'Pilih Jenis Majlis',
        'starting_from': 'Bermula dari',
        'view_packages': 'Lihat Pakej',
        'no_packages_available': 'Tiada pakej katering tersedia.',
        'contact_admin_menu': 'Pakej katering belum tersedia lagi. Sila hubungi kami terus untuk dapatkan sebut harga khas.',

        // Menu Show / Details
        'pax': 'pax',
        'included_dishes': 'Pilihan Lauk Termasuk',
        'min_requirement': 'Syarat Minimum',
        'select_quantity': 'Bilangan Tetamu (Pax)',
        'live_total': 'Harga Terkini',
        'customize_order': 'Ubah suai & Tempah',
        'direct_add_cart': 'Terus Tambah ke Troli',
        'no_packages_found_cat': 'Tiada pakej ditemui dalam kategori ini.',
        'back_to_menu': 'Kembali ke Menu',
        'scale_small': 'Majlis Kecil & Intim',
        'scale_medium': 'Kenduri Sederhana (Grand)',
        'scale_large': 'Kenduri Mega (Mega Feast)',
        'category_show_desc': 'Lihat senarai pakej hidangan yang ditawarkan khas untuk kategori ini, buat anggaran tetamu, dan tempah sekarang.',
        'cart_desc_banner': 'Semak semula pakej katering terpilih anda, laras kuantiti tetamu, dan lakukan pembayaran dengan selamat.',

        // Customizer
        'select_guest_count': 'Bilangan Tetamu (Pax)',
        'min_booking_requirement_is': 'Had minimum tempahan adalah',
        'customize_extra_items': 'Pilih Lauk Tambahan',
        'addons_desc': 'Pilih hidangan tambahan untuk dimasukkan dalam set katering anda. Harga dinyatakan adalah untuk setiap pax.',
        'price_breakdown': 'Pecahan Harga',
        'base_pkg_price': 'Harga Pakej Asas',
        'guest_count': 'Bilangan Tetamu',
        'addon_extra': 'Harga Lauk Tambahan',
        'combined_cost_pax': 'Kos Gabungan Per Pax',
        'grand_total': 'Jumlah Keseluruhan',
        'deposit_required': 'Deposit Diperlukan (30%)',
        'balance_due': 'Baki Perlu Dibayar (70%)',
        'selected_extra_items': 'Lauk Tambahan Dipilih',
        'add_to_cart': 'Tambah Ke Troli',
        'cancel': 'Batal',

        // Shopping Cart
        'package': 'Pakej',
        'price': 'Harga',
        'quantity': 'Jumlah',
        'subtotal': 'Subjumlah',
        'action': 'Tindakan',
        'order_summary': 'Ringkasan Tempahan',
        'selected_packages': 'Pakej Dipilih',
        'proceed_checkout': 'Selesaikan Tempahan',
        'continue_shopping': 'Teruskan Membeli-belah',
        'cart_empty': 'Troli anda masih kosong',
        'cart_empty_desc': 'Troli anda masih kosong! Jom lihat pakej katering kami untuk mula merancang.',
        'browse_packages_btn': 'Lihat Pakej',

        // Checkout
        'secure_checkout': 'Selesaikan Tempahan',
        'event_delivery_details': 'Butiran Majlis & Penghantaran',
        'customer_name': 'Nama Pelanggan',
        'phone_number': 'Nombor Telefon',
        'delivery_event_date': 'Tarikh Majlis',
        'preferred_delivery_time': 'Masa Penghantaran',
        'event_venue_address': 'Alamat Lokasi Majlis',
        'payment_slip_deposit': 'Muat Naik Resit Deposit (30%)',
        'deposit_commitment_desc': 'Sila imbas kod QR atau pindahkan deposit 30% ke akaun bank kami. Selepas bayar, muat naik resit di bawah supaya kami boleh sahkan dan lock tarikh majlis anda.',
        'scan_to_pay': 'Imbas & Bayar',
        'qr_not_configured': 'QR Belum Ditetapkan',
        'upload_payment_slip': 'Muat Naik Resit Bayaran',
        'select_receipt_file': 'Pilih Resit',
        'accepted_formats_desc': 'JPEG, PNG, PDF (Maksimum 4MB)',
        'confirm_booking_submit': 'Sahkan & Hantar Tempahan',
        'customer_notes': 'Nota Tambahan / Permintaan Khas',
        'customer_notes_placeholder': 'Contoh: alahan makanan, pilihan hiasan, panduan arah lokasi...',
        'delivery_tab': 'Penghantaran',
        'view_available_promos': 'Lihat Kod Promo Tersedia',
        'available_promo_codes': 'Senarai Kod Promo Tersedia',
        'no_active_promos': 'Tiada kod promo aktif buat masa ini.',
        'use_promo_code': 'Guna Kod',
        'min_spend_label': 'Belanja Minimum',
        'expires_label': 'Sah sehingga',
        'pickup_time': 'Masa Pengambilan',
        'click_to_enlarge': 'Klik untuk besarkan',

        // Bookings / Orders
        'my_bookings': 'Tempahan Saya',
        'all': 'Semua',
        'pending_rejected': 'Pending/Ditolak',
        'confirmed': 'Selesai Bayar Deposit',
        'delivered_tab': 'Dihantar',
        'awaiting_verification': 'Sedang Disemak',
        'completed_tab': 'Selesai Majlis',
        'cancelled_tab': 'Dibatalkan',
        'order_id': 'ID Tempahan',
        'delivery_event_date_label': 'Tarikh Majlis',
        'total_price': 'Jumlah Harga',
        'status_label': 'Status',
        'order_timeline_tracker': 'Jejak Status Tempahan',
        'timeline_submitted': 'Dihantar',
        'timeline_confirmed': 'Deposit Disahkan (30%)',
        'timeline_delivered': 'Dihantar',
        'timeline_completed': 'Selesai Majlis (100%)',
        'rejection_reason_admin': 'Sebab Tempahan Ditolak:',
        'view_invoice': 'Lihat Invois',
        'reupload_receipt_btn': 'Muat Naik Semula Resit',
        'cancel_event_btn': 'Batal Majlis',
        'no_bookings_found': 'Tiada tempahan setakat ini',
        'no_bookings_found_desc': 'Tiada rekod tempahan ditemui dalam bahagian ini.',
        'pending': 'Pending',
        'deposit_rejected': 'Deposit Ditolak',
        'balance_rejected': 'Baki Ditolak',
        'confirm_cancel_order': 'Adakah anda pasti mahu batalkan tempahan ini? Ingatan mesra, deposit tidak boleh dikembalikan kerana kami gunakan untuk persiapan awal.',
        'confirm_remove_cart': 'Adakah anda pasti mahu mengeluarkan pakej ini dari troli?',
        'confirm_action': 'Pengesahan Tindakan',
        'yes_confirm': 'Ya, Sahkan',
        'no_cancel': 'Batal',
        'toast_order_cancelled': 'Tempahan berjaya dibatalkan.',
        'checkout_desc_banner': 'Sahkan butiran majlis anda, muat naik resit bayaran deposit (30%), dan hantar tempahan untuk pengesahan pihak kami.',
        'file_size_error': 'Saiz fail mestilah kurang daripada 4MB.',
        'toast_receipt_uploaded': 'Resit berjaya dimuat naik!',
        'toast_added_to_cart': 'Pakej berjaya ditambah ke dalam troli!',
        'toast_order_submitted': 'Permintaan tempahan anda telah berjaya dihantar.',
        'toast_item_removed': 'Pakej berjaya dikeluarkan dari troli.',
        'toast_qty_updated': 'Bilangan tetamu berjaya dikemas kini.',
        'toast_cart_updated': 'Pilihan pakej berjaya dikemas kini!',
        'uploading': 'Memuat naik...',

        // Invoice receipt Show
        'invoice_receipt': 'Invois & Resit',
        'print_invoice': 'Cetak Invois',
        'back_to_bookings': 'Kembali ke Tempahan',
        'billed_to': 'Dibilkan Kepada',
        'event_schedule_venue': 'Jadual & Lokasi Majlis:',
        'itemized_breakdown': 'Butiran Tempahan',
        'catering_service_package': 'Pakej Perkhidmatan Katering',
        'price_pax': 'Harga / pax',
        'guest_qty': 'Jumlah Tetamu',
        'payment_trans_status': 'Status Pembayaran',
        'deposit_paid_invoice': 'Deposit Dibayar (30%)',
        'remaining_balance_invoice': 'Baki Bayaran (70%)',
        'thank_you_footer': 'Terima kasih kerana menempah dengan SmartServe Catering. Kami berbesar hati untuk menjayakan majlis anda!',
        'issued': 'Dikeluarkan',
        'email': 'E-mel',
        'phone': 'Telefon',
        'setup_time': 'Masa Persediaan',
        'venue_address': 'Alamat Tempat Majlis',
        'base_cost': 'Kos Asas',
        'payment_desc_invoice': 'Deposit tempahan sebanyak 30% telah direkodkan. Baki sebanyak (70%) dijadualkan untuk dijelaskan pada or sebelum tarikh penghantaran majlis.',

        // Dashboard Tracker & Recent Bookings
        'active_order_tracker': 'Status Tempahan Aktif',
        'no_active_order': 'Anda tidak mempunyai tempahan aktif pada masa ini.',
        'recent_bookings': 'Tempahan Terkini',
        'package_name': 'Pakej',
        'event_date': 'Tarikh Majlis',
        'pax_count': 'Jumlah Tetamu',
        'grand_total_label': 'Jumlah Keseluruhan',
        'view_details': 'Lihat Butiran',
        'no_recent_bookings': 'Tiada tempahan terkini ditemui.',
        'order_num': 'Tempahan',
        'action_required': 'Tindakan Diperlukan',
        'reupload_rejected_slip': 'Tolong muat naik semula resit pembayaran yang jelas untuk kami buat pengesahan.',
        'timeline_step_1': 'Dihantar',
        'timeline_step_2': 'Disahkan',
        'timeline_step_3': 'Dihantar',
        'timeline_step_4': 'Selesai',

        // Dynamic Dashboard
        'upcoming_event': 'Majlis Anda Akan Datang',
        'days_remaining': 'Hari Berbaki',
        'day_remaining': 'Hari Berbaki',
        'event_today': 'Majlis adalah Hari Ini!',
        'event_completed_days': 'Majlis telah berlangsung',
        'financial_summary': 'Status Kewangan',
        'deposit_paid': 'Deposit Dibayar (30%)',
        'balance_due_payment': 'Baki Perlu Dibayar (70%)',
        'upload_balance_receipt': 'Muat Naik Resit Baki Bayaran (70%)',
        'balance_submitted_verification': 'Resit baki bayaran sedang disemak.',
        'featured_packages_title': 'Pakej Menarik Untuk Anda',
        'featured_packages_subtitle': 'Pakej terbaik yang disusun khas mengikut kesesuaian majlis anda.',
        'catering_guidelines': 'Tips & Panduan Majlis',
        'guide_pax_title': 'Berapa pax tetamu patut saya tempah?',
        'guide_pax_desc': 'Kami cadangkan anda tempah 10% lebih daripada jumlah jemputan sebagai langkah selamat. Pakej kami mempunyai syarat minimum pax (contohnya 50 atau 100 orang).',
        'guide_halal_title': 'Keselamatan Makanan & Jaminan Halal',
        'guide_halal_desc': 'Kakitangan kami memasak di dapur yang bersih. Makanan dihantar menggunakan kotak bekas terma khas untuk mengekalkan rasa segar dan panas.',
        'guide_changes_title': 'Cara membuat perubahan menu',
        'guide_changes_desc': 'Tolong sahkan jumlah tetamu dan sebarang tambahan menu sekurang-kurangnya 7 hari sebelum majlis untuk mudahkan penyediaan bahan.',

        // Budget Planner
        'calc_by_budget': 'Cari Ikut Bajet',
        'calc_by_guest': 'Cari Ikut Bilangan Tetamu',
        'enter_target_budget': 'Masukkan Bajet Anda (RM)',
        'enter_guest_count': 'Masukkan Jumlah Tetamu (Orang)',
        'calculate_btn': 'Kira Cadangan Pakej',
        'recommendations': 'Pakej Cadangan Kami',
        'select_customize_btn': 'Pilih & Ubah suai',
        'leftover_budget': 'Baki Bajet',
        'pax_recommended': 'Jumlah Tetamu Disyorkan',
        'no_results_found': 'Tiada pakej yang sepadan dengan bajet/jumlah tetamu anda.',
        'no_results_desc': 'Cuba tingkatkan bajet anda atau kurangkan sedikit bilangan tetamu.',
        'step_planning_mode': 'Langkah 1: Pilih Cara Rancang',
        'step_base_package': 'Langkah 2: Pilih Pakej Pilihan',
        'step_addons': 'Langkah 3: Tambah Lauk/Barangan Lain (Pilihan)',
        'live_estimate': 'Anggaran Harga Terkini',
        'book_customize_plan': 'Tempah & Ubah suai Pakej',
        'budget_exceeded': 'Terlebih Bajet Sebanyak',
        'within_budget': 'Cukup Bajet!',
        'insufficient_budget': 'Bajet tidak mencukupi untuk tempahan minimum pakej.',
        'insufficient_budget_desc': 'Bajet anda nampaknya kurang daripada syarat tempahan minimum pakej ini. Cuba laraskan bajet atau pilih pakej lain.',
        'auto_adjusted_min': 'Jumlah tetamu dilaraskan automatik kepada minimum pakej.',
        'reviews_ratings': 'Ulasan & Rating',
        'write_review': 'Tulis Ulasan',
        'review_rating': 'Rating / Bintang',
        'review_comment': 'Ulasan Anda',
        'review_comment_placeholder': 'Kongsi pengalaman anda tentang makanan dan servis kami...',
        'submit_review': 'Hantar Ulasan',
        'admin_reply_label': 'Balasan daripada Kami',
        'no_reviews_yet': 'Belum ada ulasan untuk pakej ini.',
        'review_success': 'Terima kasih atas ulasan anda!',
        'review_stars': 'Bintang',
        'overall_rating': 'Rating Keseluruhan',
        'customer_testimonials': 'Apa Kata Pelanggan Kami',
        'promo_code': 'Kod Promo',
        'apply_promo_btn': 'Guna Kod',
        'promo_applied': 'Kod Promo Berjaya Diguna',
        'discount': 'Diskaun',
        'fully_booked_date': 'Tarikh Penuh / Tidak Tersedia',

        // New Landing Page Translations
        'our_packages': 'Pakej',
        'faq': 'Soalan Lazim',
        'contact_us': 'Hubungi Kami',
        'about_subtitle': 'BEROPERASI DI GONG BADAK',
        'about_title_1': 'Menyediakan Hidangan Sedap',
        'about_title_2': 'Untuk Majlis Istimewa Anda',
        'about_desc_1': 'SmartServe Catering bermula dengan impian untuk menyajikan lauk-pauk Pantai Timur yang sedap untuk majlis anda. Kami pakar dalam menyediakan hidangan tradisional yang lazat dengan hiasan meja bufet yang kemas.',
        'about_desc_2': 'Sama ada untuk kenduri kecil-kecilan, majlis kahwin, atau jamuan pejabat, kami sedia uruskan semuanya supaya anda boleh berehat dan melayan tetamu dengan tenang.',
        'stats_events': 'Acara Dikendalikan',
        'stats_guests': 'Tetamu Dihidang',
        'stats_halal': 'Jaminan Halal',
        'stats_recipes': 'Hidangan Istimewa',
        'stats_halal_val': '100% Halal',
        'values_title': 'Prinsip Servis Kami',
        'value_1_title': 'Resepi Asli',
        'value_1_desc': 'Kami kekalkan rasa masakan asli Terengganu dengan menggunakan bahan-bahan segar dari pasar tempatan.',
        'value_2_title': 'Jaga Bajet',
        'value_2_desc': 'Kami uruskan setiap tempahan dengan baik supaya anda mendapat kualiti makanan terbaik mengikut bajet anda.',
        'value_3_title': 'Kemas & Bersih',
        'value_3_desc': 'Susun atur meja bufet dan meja makan yang kemas serta bersih untuk keselesaan tetamu majlis.',
        'packages_title': 'Pakej Katering Yang Tersedia',
        'packages_subtitle': 'Pilih pakej yang sesuai untuk majlis anda. Klik "Ubah suai" untuk menukar menu lauk atau bilangan tetamu mengikut cita rasa anda.',
        'customize_this_package': 'Ubah suai Pakej',
        'faq_title': 'Soalan Yang Sering Ditanya',
        'faq_subtitle': 'Ada soalan? Berikut adalah senarai jawapan kepada soalan yang paling kerap ditanya oleh pelanggan kami.',
        'faq_q1': 'Adakah makanan katering anda Halal?',
        'faq_a1': 'Ya, semestinya! Semua bahan masakan kami dibeli dari pembekal Halal yang sah dan kami memasak di dapur yang bersih dan kemas.',
        'faq_q2': 'Bila saya perlu tetapkan jumlah tetamu yang muktamad?',
        'faq_a2': 'Sila sahkan jumlah tetamu dan menu akhir sekurang-kurangnya 7 hari sebelum tarikh majlis untuk memudahkan persiapan bahan mentah.',
        'faq_q3': 'Adakah anda menghantar ke luar Kuala Terengganu?',
        'faq_a3': 'Kami melayani kawasan Kuala Terengganu, Kuala Nerus, Gong Badak, dan Marang. Kalau majlis di luar kawasan ini, boleh hubungi kami untuk bincang tentang kos pengangkutan.',
        'faq_q4': 'Bagaimana makanan kekal segar dan panas semasa dihantar?',
        'faq_a4': 'Semua lauk panas dimasukkan ke dalam bekas terma khas agar makanan kekal panas, segar, dan sedap dimakan apabila tiba di majlis.',
        'faq_q5': 'Boleh ke saya tukar lauk dalam pakej?',
        'faq_a5': 'Ya, boleh sangat! Anda boleh gunakan butang Ubah Suai Menu untuk tukar lauk pilihan kepada lauk lain dalam kategori sama secara percuma, atau tambah add-on.',
        'contact_title': 'Hubungi Kami',
        'contact_subtitle': 'Ada soalan atau mahu bincang pasal menu majlis anda? Hantar mesej melalui borang di bawah atau terus WhatsApp kami!',
        'contact_name': 'Nama Anda',
        'contact_email': 'Alamat E-mel',
        'contact_phone': 'Nombor Telefon',
        'contact_date': 'Tarikh Acara',
        'contact_pax': 'Bilangan Tetamu',
        'contact_type': 'Jenis Majlis / Acara',
        'contact_message': 'Mesej / Permintaan Khas Anda',
        'contact_submit': 'Hantar Pertanyaan',
        'contact_whatsapp_btn': 'Sembang di WhatsApp',
        'contact_type_wedding': 'Perkahwinan / Resepsi',
        'contact_type_corporate': 'Acara Korporat',
        'contact_type_social': 'Perhimpunan Peribadi / Parti',
        'contact_type_other': 'Majlis Lain',
        'inquiry_success': 'Mesej anda berjaya dihantar! Terima kasih, kami akan hubungi anda semula secepat mungkin.',
        'inquiry_whatsapp_text': 'Hai SmartServe Catering! Saya ingin bertanya tentang pakej katering. Berikut adalah butiran saya:\nNama: {name}\nTarikh Majlis: {date}\nTetamu: {pax} pax\nJenis Majlis: {type}\nMesej: {message}',
        // Additions for landing pages
        'booking_policies_title': 'Terma & Syarat Tempahan',
        'booking_policies_subtitle': 'Sila baca dan fahami terma & syarat kami sebelum membuat sebarang tempahan.',
        'policy_header_3': 'Perubahan Menu',
        'policy_desc_3': 'Anda boleh tukar lauk menu sehingga 7 hari sebelum majlis. Sebarang perubahan selepas itu bergantung pada stok bahan dapur dan mungkin ada caj tambahan.',
        'policy_header_4': 'Jumlah Tetamu',
        'policy_desc_4': 'Sila sahkan bilangan tetamu 3 hari sebelum majlis. Sebarang pertambahan lauk saat akhir akan dikenakan caj tambahan mengikut kadar semasa.',
        'policy_header_5': 'Jaminan Halal',
        'policy_desc_5': 'Semua lauk pauk kami dijamin 100% Halal. Kami dapatkan bahan mentah dari pembekal yang disahkan Halal dan menjaga kebersihan dapur.',
        'policy_header_6': 'Penyelesaian Aduan',
        'policy_desc_6': 'Jika ada maklum balas atau aduan, sila beritahu kami dalam masa 24 jam selepas majlis tamat supaya kami dapat selesaikan dengan baik.',
        'agreement_banner_title': 'Persetujuan Servis',
        'agreement_banner_desc': 'Sebaik sahaja anda membayar deposit, anda dianggap bersetuju dengan terma dan syarat kami. Terima kasih kerana memilih kami!',
        'ask_us': 'Tanya Kami',
        'view_all_questions': 'Lihat Semua Soalan',
        'q_min_guests': 'Berapakah bilangan minimum tetamu?',
        'q_halal': 'Adakah makanan bersijil Halal?',
        'q_menu_change': 'Bolehkah menu diubahsuai?',
        'q_payment': 'Apakah kaedah bayaran diterima?',
        'about_quote': '"Kami tidak sekadar menyajikan makanan — kami mencipta kenangan abadi di setiap majlis yang kami hidangkan."',
        'achievements_title': 'Pencapaian Kami',
        'milestones_title': 'Perjalanan Kami',
        'milestones_subtitle': 'Dari Gong Badak ke Seluruh Terengganu',
        'journey_2009_title': 'Permulaan Kecil',
        'journey_2009_desc': 'SmartServe mula beroperasi sebagai perkhidmatan katering majlis kampung di kawasan Gong Badak dengan kakitangan yang kecil tetapi penuh semangat.',
        'journey_2015_title': 'Berkembang ke Kuala Terengganu',
        'journey_2015_desc': 'Kami memperluas perkhidmatan ke bandar raya Kuala Terengganu dan mula menerima tempahan majlis perkahwinan besar dengan lebih 1,000 tetamu.',
        'journey_2020_title': 'Digitalisasi Sistem',
        'journey_2020_desc': 'Kami memperkenalkan sistem tempahan dalam talian SmartServe untuk memudahkan pelanggan membuat pesanan, menyesuaikan menu, dan membuat bayaran terus dari rumah.',
        'journey_now_title': 'Kini',
        'journey_now_desc': 'Dengan lebih 500 majlis yang berjaya, SmartServe kini menjadi nama paling dipercayai dalam industri katering di Terengganu.',
        'ready_dream_event': 'Bersedia untuk majlis impian anda?',
        'ready_dream_desc': 'Hubungi kami hari ini untuk perbincangan percuma tentang pakej katering yang sesuai untuk majlis anda.',
        'start_journey_title': 'Mula Perjalanan Anda',
        'connect_coordinates': 'Koordinat Kami',
        'address_label': 'Alamat Kami',
        'hotline_label': 'Hotline Langsung',
        'email_label': 'E-mel',
        'whatsapp_click_desc': 'Klik untuk WhatsApp terus',
        'service_area_desc': 'Kami menyediakan perkhidmatan katering untuk pelbagai jenis majlis di seluruh kawasan Kuala Terengganu, Kuala Nerus, Gong Badak, Marang, dan sekitarnya.',
        'business_hours_title': 'Waktu Operasi',
        'weekday_label': 'Isnin – Jumaat',
        'saturday_label': 'Sabtu',
        'sunday_label': 'Ahad',
        'booking_only_label': 'Tempahan sahaja',
        'contact_reply_notice': 'Kami akan menghubungi anda semula dalam masa 24 jam.',
        'faq_q1_text': 'Berapakah bilangan minimum tetamu untuk membuat tempahan?',
        'faq_a1_text': 'Kebanyakan pakej memerlukan tempahan minimum 100 orang. Untuk pakej perkahwinan pula minimum 500 orang. Boleh hubungi kami kalau nak bincang lanjut.',
        'faq_q2_text': 'Berapa lama proses tempahan dan pengesahan?',
        'faq_a2_text': 'Kami akan sahkan tempahan dalam masa 1-2 hari bekerja. Selepas deposit diterima, kami akan hubungi anda untuk bincang pasal menu.',
        'faq_q3_text': 'Adakah anda menawarkan perkhidmatan di luar kawasan Terengganu?',
        'faq_a3_text': 'Sekarang kami cover kawasan Kuala Terengganu, Kuala Nerus, Gong Badak, dan Marang. Kalau luar dari kawasan ini, sila WhatsApp kami dahulu.',
        'faq_q4_text': 'Bolehkah menu diubahsuai mengikut keperluan khas?',
        'faq_a4_text': 'Ya, anda bebas menukar lauk pilihan. Cuma tolong beritahu kami 7 hari sebelum majlis. Kami juga boleh sediakan hidangan vegetarian jika diminta.',
        'faq_q5_text': 'Apakah kaedah bayaran yang diterima?',
        'faq_a5_text': 'Anda boleh bayar guna bank transfer (FPX), tunai, atau e-wallet. Deposit 30% diperlukan untuk lock tarikh majlis, dan baki bayaran selebihnya perlu dijelaskan 3 hari sebelum tarikh majlis.',
        'faq_q6_text': 'Adakah makanan anda bersijil Halal?',
        'faq_a6_text': 'Ya, 100% Halal. Kami beli bahan mentah daripada pembekal yang ada sijil Halal JAKIM.',
        'faq_q7_text': 'What is included in the basic package?',
        'faq_a7_text': 'Pakej asas dah masuk lauk pauk, pinggan/cawan/sudu, meja bufet, dan pelayan. Kalau nak tambah khemah, meja, atau kerusi tetamu, boleh tambah sebagai add-on.',
        'faq_q8_text': 'Bagaimana jika majlis perlu dibatalkan?',
        'faq_a8_text': 'Batal 30 hari sebelum majlis: deposit dipulangkan penuh. Batal 14-30 hari: dipulangkan 50%. Batal kurang 14 hari: deposit tidak boleh dipulangkan.',
        // Packages Page Keys
        'packages_hero_title_1': 'Pakej Katering',
        'packages_hero_title_2': 'Kami',
        'packages_hero_desc': 'Pilih pakej yang sesuai untuk majlis anda. Semua pakej boleh disesuaikan mengikut keperluan dan bajet anda.',
        'min_booking': 'Min. Tempahan',
        'select_package': 'Pilih Pakej',
        'special_package': 'Pakej Khas',
        'want_something_special': 'Ingin Pakej Yang Lebih Istimewa?',
        'custom_menu_desc': 'Kami boleh mereka bentuk menu khusus mengikut tema, bajet, dan keperluan majlis anda.',
        'mock_pkg_1_name': 'Wedding Silver',
        'mock_pkg_1_desc': 'Pakej bufet perkahwinan klasik dengan resepi lauk tradisional, ayam, daging kerutuk, dan pencuci mulut tempatan.',
        'mock_pkg_2_name': 'Corporate Bronze',
        'mock_pkg_2_desc': 'Set acara profesional dengan resepi fusion kontemporari, minuman panas, pastri, dan makanan tempatan kegemaran.',
        'mock_pkg_3_name': 'Aqiqah & Gathering',
        'mock_pkg_3_desc': 'Pakej jamuan tradisional dengan kari kambing, dalca signature, nasi minyak aromatik, dan lauk-pauk tradisional.',
        // FrontLayout Navbar & Footer
        'home_nav': 'Laman Utama',
        'about_nav': 'Tentang Kami',
        'package_nav': 'Pakej',
        'faq_nav': 'FAQ',
        'contact_nav': 'Hubungi Kami',
        'explore_title': 'Terokai',
        'connect_title': 'Hubungi',
        'footer_desc': 'Kami menyediakan khidmat katering di sekitar Terengganu dengan hidangan lauk-pauk yang sedap dan hiasan bufet yang kemas.',
        // FrontLayout Auth Drawers
        'reset_password': 'Reset Kata Laluan',
        'set_new_password': 'Tetapkan Kata Laluan Baru',
        'email_address_label': 'Alamat E-mel',
        'password_label': 'Kata Laluan',
        'forgot_password_btn': 'Lupa Kata Laluan?',
        'remember_session': 'Ingat sesi saya',
        'signing_in_status': 'Log Masuk...',
        'no_account_notice': 'Belum ada akaun?',
        'your_name_label': 'Nama Anda',
        'full_name_label': 'Nama Penuh',
        'phone_number_label': 'Nombor Telefon',
        'delivery_address_label': 'Alamat Rumah / Majlis',
        'confirm_password_label': 'Sahkan Kata Laluan',
        'registering_status': 'Mendaftar...',
        'already_registered_notice': 'Sudah ada akaun?',
        'forgot_password_desc': 'Lupa kata laluan? Jangan risau. Masukkan alamat e-mel anda di bawah dan kami akan hantar pautan untuk set kata laluan baru.',
        'send_reset_link_btn': 'Hantar Pautan Reset',
        'sending_status': 'Menghantar...',
        'back_to_btn': 'Kembali ke',
        'current_password': 'Kata Laluan Semasa',
        'new_password_label': 'Kata Laluan Baru',
        'confirm_new_password_label': 'Sahkan Kata Laluan Baru',
        'resetting_status': 'Menetapkan Semula...',
        'read_more': 'Baca Lebih Lanjut',
        'view_all_packages': 'Lihat Semua Pakej',
        'testimonials_subtitle': 'Baca maklum balas jujur dan ulasan daripada pelanggan yang pernah menggunakan perkhidmatan kami.',
        'years_serving': 'Tahun Pengalaman',
        'milestones_tag': 'Perjalanan Kami',
        'faq_title_1': 'Soalan',
        'faq_title_2': 'Kerap',
        'faq_title_3': 'Ditanya',
        'faq_subtitle_desc': 'Cari jawapan kepada soalan-soalan yang sering ditanyakan tentang tempahan, menu, dan polisi katering kami.',
        'still_have_questions': 'Masih Ada Soalan?',
        'still_have_questions_desc': 'Hubungi kami terus sekarang! Kami sedia membantu menjawab apa-apa soalan anda.',
        'error_name_required': 'Nama diperlukan.',
        'error_email_required': 'E-mel diperlukan.',
        'error_email_invalid': 'E-mel tidak sah.',
        'error_phone_required': 'Nombor telefon diperlukan.',
        'error_date_required': 'Tarikh majlis diperlukan.',
        'error_pax_required': 'Bilangan tetamu diperlukan.',
        'error_message_required': 'Mesej diperlukan.',
        'placeholder_name': 'Nama anda',
        'placeholder_email': 'email@contoh.com',
        'placeholder_phone': '+60 12-345 6789',
        'placeholder_pax': 'Contoh: 500',
        'placeholder_message': 'Ceritakan lebih lanjut tentang majlis anda...',
        'values_desc': 'Kami berpegang teguh kepada prinsip utama ini bagi menjamin kualiti hidangan terbaik untuk majlis anda.',
        'now_label': 'Kini',
        'profile_information': 'Maklumat Profil',
        'profile_info_desc': 'Kemas kini maklumat profil dan alamat e-mel akaun anda.',
        'update_password': 'Kemas Kini Kata Laluan',
        'update_password_desc': 'Pastikan akaun anda menggunakan kata laluan yang panjang dan rawak untuk kekal selamat.',
        'delete_account': 'Padam Akaun',
        'delete_account_desc': 'Setelah akaun anda dipadamkan, semua data dan sumbernya akan dipadamkan secara kekal. Sila muat turun sebarang maklumat yang ingin anda simpan sebelum memadamkan akaun.',
        'delete_confirm_title': 'Adakah anda pasti mahu memadamkan akaun anda?',
        'delete_confirm_desc': 'Setelah akaun anda dipadamkan, semua data dan sumbernya akan dipadamkan secara kekal. Sila masukkan kata laluan anda untuk mengesahkan bahawa anda ingin memadamkan akaun secara kekal.',
        'personal_account': 'Akaun Peribadi',
        'save_changes': 'Simpan Perubahan',
        'email_verified_success': 'E-mel berjaya disahkan! Selamat datang ke dashboard anda.',
        'session_expired_title': 'Sesi Anda Telah Tamat',
        'session_expired_desc': 'Sesi anda telah tamat kerana tidak aktif. Sila log masuk semula untuk meneruskan.'
    }
};

export function useLocalization() {
    const t = (key) => {
        return translations[locale.value]?.[key] || translations['en']?.[key] || key;
    };

    const setLanguage = (lang) => {
        locale.value = lang;
        localStorage.setItem('ssc_locale', lang);
    };

    const currentLanguage = computed(() => locale.value);

    return {
        t,
        setLanguage,
        currentLanguage,
    };
}
