import { ref, computed } from 'vue';

const locale = ref(localStorage.getItem('ssc_locale') || 'en');

const translations = {
    en: {
        // Navigation / General
        'our_story': 'Our Story',
        'philosophy': 'Philosophy',
        'policies': 'Policies',
        'dashboard': 'Dashboard',
        'sign_in': 'Sign In',
        'register': 'Register',
        'logout': 'Log Out',
        'packages': 'Packages',
        'orders': 'Orders',
        'profile': 'Profile',
        'menu': 'Menu',

        // Welcome / Public landing page
        'hero_subtitle': 'Fine Catering & Events — Gong Badak',
        'hero_title_1': 'Traditional Flavors',
        'hero_title_2': 'Artfully Presented',
        'hero_title_3': 'For Unforgettable Moments',
        'hero_desc': 'Elevate your wedding, corporate banquet, or private gathering with the culinary heritage of Kuala Terengganu. We weave authentic spices into contemporary gourmet menus, coupled with minimalist, seamless coordination.',
        'begin_experience': 'Begin Experience',
        'read_story': 'Read Our Story',
        'service_standard': 'OUR SERVICE STANDARD',
        'service_standard_desc': 'Refined, punctual, and curated to your exact vision.',
        'story_title_1': '01 / Culinary Craft',
        'story_header_1': 'Sourced Locally, Served Excellently',
        'story_desc_1': 'We curate local organic ingredients from Terengganu, cooked under rigorous culinary hygiene frameworks to ensure pristine quality on every banquet table.',
        'story_title_2': '02 / Seamless Planning',
        'story_header_2': 'Dynamic Customization',
        'story_desc_2': 'Our proprietary Budget Planner automates the menu curation process, allowing you to instantly align gourmet options with your guest numbers or wallet bounds.',
        'philosophy_tag': 'OUR PHILOSOPHY',
        'philosophy_title_1': 'Elevating the Heritage of',
        'philosophy_title_2': 'East Coast Gastronomy',
        'philosophy_desc_1': 'Traditional culinary traditions deserve elegant representation. By combining time-tested recipes of Terengganu—from local aromatic herbs to slow-roasted marinades—with minimalist presentation, we create dishes that delight both the palate and the eye.',
        'philosophy_desc_2': 'Every menu element is thoughtfully portioned, styled, and delivered in specialized thermal containers to ensure fresh flavors are sealed at the perfect serving temperature.',
        'browse_packages': 'Browse Guest Packages',
        'booking_policies': 'Booking Policies',
        'policy_title_1': '01 / DEPOSIT',
        'policy_header_1': '30% Reservation Commitment',
        'policy_desc_1': 'A 30% booking deposit is required to lock your requested event date. Please note that all deposits are non-refundable in the event of custom cancellations to cover initial ingredient sourcing.',
        'policy_title_2': '02 / CANCELLATION',
        'policy_header_2': '7-Day Notice Policy',
        'policy_desc_2': 'Any reservation cancellations or major changes to the guest headcount must be finalized at least 7 days prior to the scheduled delivery date. Late notifications will forfeit the deposit.',
        'policy_title_3': '03 / SANITATION',
        'policy_header_3': 'Culinary Safety & Halal',
        'policy_desc_3': 'All catering operations maintain 100% Halal certification. Food items are cooked and sealed within thermal containment boxes to ensure safety standards.',
        'copyright': 'SmartServe Catering Gong Badak. All rights reserved.',

        // Customer Dashboard
        'welcome_back': 'Welcome back',
        'welcome_desc': "Let's collaborate to make your next catering experience completely seamless and culinary excellent.",
        'order_now': 'Order Now',
        'shopping_cart': 'Shopping Cart',
        'total_bookings': 'Total Bookings',
        'quick_actions': 'Quick Actions',
        'our_menu': 'Our Menu',
        'our_menu_desc': 'Explore traditional Kuala Terengganu sets and customizable packages.',
        'browse_menu': 'Browse Menu',
        'budget_planner': 'Budget Planner',
        'budget_planner_desc': 'Enter budget parameters and get instant package recommendations.',
        'open_planner': 'Open Planner',
        'my_orders': 'My Orders',
        'my_orders_desc': 'Review order milestones, deposit statuses, and event schedules.',
        'track_orders': 'Track Orders',
        'edit_profile': 'Edit Profile',
        'edit_profile_desc': 'Configure contact details, saved delivery addresses, and settings.',
        'settings': 'Settings',

        // Menu Index / Catalog
        'catering_packages': 'Catering Packages',
        'premium_selection': 'PREMIUM SELECTION',
        'select_occasion': 'Select Your Occasion',
        'starting_from': 'Starting from',
        'view_packages': 'View Packages',
        'no_packages_available': 'No catering packages available.',
        'contact_admin_menu': 'Please contact administrators to add menus.',

        // Menu Show / Details
        'pax': 'pax',
        'included_dishes': 'Included Dishes',
        'min_requirement': 'Minimum Requirement',
        'select_quantity': 'Select Quantity (Pax)',
        'live_total': 'Live Total',
        'customize_order': 'Customize & Order',
        'direct_add_cart': 'Direct Add to Cart',
        'no_packages_found_cat': 'No packages found in this category.',
        'back_to_menu': 'Back to Menu',

        // Customizer
        'select_guest_count': 'Select Guest Count (Pax)',
        'min_booking_requirement_is': 'Minimum booking requirement is',
        'customize_extra_items': 'Customize Extra Items',
        'addons_desc': 'Select additional items to add to your catering set. Prices listed are per pax.',
        'price_breakdown': 'Price Breakdown',
        'base_pkg_price': 'Base Package Price',
        'guest_count': 'Guest Count',
        'addon_extra': 'Tambahan Add-on',
        'combined_cost_pax': 'Combined Cost Per Pax',
        'grand_total': 'Grand Total',
        'deposit_required': 'Deposit Required (30%)',
        'balance_due': 'Balance Due (70%)',
        'selected_extra_items': 'Selected Extra Items',
        'add_to_cart': 'Add to Shopping Cart',
        'cancel': 'Cancel',

        // Shopping Cart
        'package': 'Package',
        'price': 'Price',
        'quantity': 'Quantity',
        'subtotal': 'Subtotal',
        'action': 'Action',
        'order_summary': 'Order Summary',
        'selected_packages': 'Selected Packages',
        'proceed_checkout': 'Proceed to Checkout',
        'continue_shopping': 'Continue Shopping',
        'cart_empty': 'Your cart is empty',
        'cart_empty_desc': "You haven't added any catering packages to your shopping cart yet.",
        'browse_packages_btn': 'Browse Packages',

        // Checkout
        'secure_checkout': 'Secure Checkout',
        'event_delivery_details': 'Event Delivery Details',
        'customer_name': 'Customer Name',
        'phone_number': 'Phone Number',
        'delivery_event_date': 'Delivery Event Date',
        'preferred_delivery_time': 'Preferred Delivery Time',
        'event_venue_address': 'Event Venue Address',
        'payment_slip_deposit': 'Payment Receipt Upload (30% Deposit)',
        'deposit_commitment_desc': 'Scan the QR code below or transfer the required 30% deposit amount of to our bank account. Once paid, please upload your transaction receipt image/PDF below to secure your date.',
        'scan_to_pay': 'Scan to Pay',
        'qr_not_configured': 'QR Not Configured',
        'upload_payment_slip': 'Upload Payment Slip / Receipt',
        'select_receipt_file': 'Select receipt file',
        'accepted_formats_desc': 'JPEG, PNG, PDF (Max 4MB)',
        'confirm_booking_submit': 'Confirm Booking & Submit',

        // Bookings / Orders
        'my_bookings': 'My Bookings',
        'all': 'All',
        'pending_rejected': 'Pending/Rejected',
        'confirmed': 'Confirmed',
        'delivered_tab': 'Delivered',
        'awaiting_verification': 'Awaiting Verification',
        'completed_tab': 'Completed',
        'cancelled_tab': 'Cancelled',
        'order_id': 'Order ID',
        'delivery_event_date_label': 'Delivery Event Date',
        'total_price': 'Total Price',
        'status_label': 'Status',
        'order_timeline_tracker': 'Order Timeline Tracker',
        'timeline_submitted': 'Submitted',
        'timeline_confirmed': 'Confirmed (30%)',
        'timeline_delivered': 'Delivered',
        'timeline_completed': 'Completed (100%)',
        'rejection_reason_admin': 'Rejection Reason from Administrator:',
        'view_invoice': 'View Invoice',
        'reupload_receipt_btn': 'Re-upload Receipt',
        'cancel_event_btn': 'Cancel Event',
        'no_bookings_found': 'No bookings found',
        'no_bookings_found_desc': 'You do not have any active or past catering bookings registered under this filter.',
        'pending': 'Pending',
        'deposit_rejected': 'Deposit Rejected',
        'balance_rejected': 'Balance Rejected',
        'confirm_cancel_order': 'Are you sure you want to cancel this order? Please note that deposits are non-refundable.',
        'toast_order_cancelled': 'Order cancelled successfully.',
        'file_size_error': 'File size must be less than 4MB.',
        'toast_receipt_uploaded': 'New receipt uploaded successfully!',
        'uploading': 'Uploading...',

        // Invoice receipt Show
        'invoice_receipt': 'Invoice & Receipt',
        'print_invoice': 'Print Invoice',
        'back_to_bookings': 'Back to Bookings',
        'billed_to': 'Billed To',
        'event_schedule_venue': 'Event Schedule & Venue:',
        'itemized_breakdown': 'Itemized Breakdown',
        'catering_service_package': 'Catering Service Package',
        'price_pax': 'Price / pax',
        'guest_qty': 'Guest Qty',
        'payment_trans_status': 'Payment Transaction Status',
        'deposit_paid_invoice': 'Deposit Paid (30%)',
        'remaining_balance_invoice': 'Remaining Balance (70%)',
        'thank_you_footer': 'Thank you for booking with SmartServe Catering. This invoice serves as a receipt of registration.',
        'issued': 'Issued',
        'email': 'Email',
        'phone': 'Phone',
        'setup_time': 'Setup Time',
        'venue_address': 'Venue Address',
        'base_cost': 'Base Cost',
        'payment_desc_invoice': 'The 30% reservation deposit has been logged. The remaining balance (70%) is scheduled to be settled on or before the delivery event date.'
    },
    my: {
        // Navigation / General
        'our_story': 'Kisah Kami',
        'philosophy': 'Falsafah',
        'policies': 'Polisi',
        'dashboard': 'Dashboard',
        'sign_in': 'Log Masuk',
        'register': 'Daftar',
        'logout': 'Log Keluar',
        'packages': 'Pakej',
        'orders': 'Tempahan',
        'profile': 'Profil',
        'menu': 'Menu',

        // Welcome / Public landing page
        'hero_subtitle': 'Katering & Acara Eksklusif — Gong Badak',
        'hero_title_1': 'Rasa Tradisional',
        'hero_title_2': 'Dihidang Estetik',
        'hero_title_3': 'Untuk Momen Terindah',
        'hero_desc': 'Serikan hari perkahwinan, jamuan korporat, atau majlis peribadi anda dengan warisan kulinari Kuala Terengganu. Kami menyatukan rempah ratus asli ke dalam menu gourmet kontemporari, disulam dengan penyelarasan yang lancar dan minimalis.',
        'begin_experience': 'Mula Pengalaman',
        'read_story': 'Baca Kisah Kami',
        'service_standard': 'STANDARD PERKHIDMATAN KAMI',
        'service_standard_desc': 'Kemas, menepati masa, dan disesuaikan mengikut impian anda.',
        'story_title_1': '01 / Seni Kulinari',
        'story_header_1': 'Sumber Tempatan, Hidangan Gemilang',
        'story_desc_1': 'Kami memilih bahan organik tempatan dari Terengganu, dimasak di bawah rangka kerja kebersihan kulinari yang ketat untuk memastikan kualiti terbaik di setiap meja jamuan.',
        'story_title_2': '02 / Perancangan Mudah',
        'story_header_2': 'Kustomisasi Dinamik',
        'story_desc_2': 'Perancang Bajet proprietari kami memudahkan proses pemilihan menu, membolehkan anda memadankan pilihan gourmet dengan bilangan tetamu atau had bajet anda secara langsung.',
        'philosophy_tag': 'FALSAFAH KAMI',
        'philosophy_title_1': 'Mengangkat Warisan',
        'philosophy_title_2': 'Gastronomi Pantai Timur',
        'philosophy_desc_1': 'Tradisi kulinari tradisional layak mendapat persembahan yang elegan. Dengan menggabungkan resipi Terengganu yang teruji masa—daripada herba aromatik tempatan kepada perapan panggang perlahan—dengan persembahan minimalis, kami menghasilkan hidangan yang memikat rasa dan pandangan.',
        'philosophy_desc_2': 'Setiap elemen menu diasingkan, digayakan, dan dihantar dalam bekas terma khas dengan teliti untuk memastikan rasa segar kekal terpelihara pada suhu hidangan yang sempurna.',
        'browse_packages': 'Lihat Pakej Tetamu',
        'booking_policies': 'Polisi Tempahan',
        'policy_title_1': '01 / DEPOSIT',
        'policy_header_1': 'Komitmen Tempahan 30%',
        'policy_desc_1': 'Deposit tempahan sebanyak 30% diperlukan untuk menetapkan tarikh acara anda. Sila ambil perhatian bahawa semua deposit adalah tidak boleh dikembalikan sekiranya berlaku pembatalan bagi menampung kos penyediaan bahan awal.',
        'policy_title_2': '02 / PEMBATALAN',
        'policy_header_2': 'Polisi Notis 7 Hari',
        'policy_desc_2': 'Sebarang pembatalan tempahan atau perubahan besar kepada bilangan tetamu mestilah diselesaikan sekurang-kurangnya 7 hari sebelum tarikh penghantaran yang dijadualkan. Pemberitahuan lewat akan menyebabkan deposit hangus.',
        'policy_title_3': '03 / SANITASI',
        'policy_header_3': 'Keselamatan Kulinari & Halal',
        'policy_desc_3': 'Semua operasi katering mengekalkan pensijilan 100% Halal. Makanan dimasak dan dikurung dalam kotak bekas terma untuk memastikan piawaian keselamatan terpelihara.',
        'copyright': 'SmartServe Catering Gong Badak. Hak cipta terpelihara.',

        // Customer Dashboard
        'welcome_back': 'Selamat kembali',
        'welcome_desc': 'Mari bekerjasama untuk menjadikan pengalaman katering anda yang seterusnya berjalan lancar dan cemerlang dari segi kulinari.',
        'order_now': 'Tempah Sekarang',
        'shopping_cart': 'Troli Beli-belah',
        'total_bookings': 'Jumlah Tempahan',
        'quick_actions': 'Tindakan Pantas',
        'our_menu': 'Menu Kami',
        'our_menu_desc': 'Terokai set tradisional Kuala Terengganu dan pakej yang boleh dikustomkan.',
        'browse_menu': 'Lihat Menu',
        'budget_planner': 'Perancang Bajet',
        'budget_planner_desc': 'Masukkan bajet anda dan dapatkan cadangan pakej katering secara serta-merta.',
        'open_planner': 'Buka Perancang',
        'my_orders': 'Tempahan Saya',
        'my_orders_desc': 'Semak status tempahan, deposit, dan jadual acara katering anda.',
        'track_orders': 'Jejak Tempahan',
        'edit_profile': 'Edit Profil',
        'edit_profile_desc': 'Urus maklumat hubungan, alamat penghantaran dan tetapan profil akaun.',
        'settings': 'Tetapan',

        // Menu Index / Catalog
        'catering_packages': 'Pakej Katering',
        'premium_selection': 'PILIHAN PREMIUM',
        'select_occasion': 'Pilih Acara Anda',
        'starting_from': 'Bermula dari',
        'view_packages': 'Lihat Pakej',
        'no_packages_available': 'Tiada pakej katering tersedia.',
        'contact_admin_menu': 'Sila hubungi pentadbir untuk menambah menu katering.',

        // Menu Show / Details
        'pax': 'pax',
        'included_dishes': 'Hidangan Termasuk',
        'min_requirement': 'Syarat Minimum',
        'select_quantity': 'Pilih Bilangan Tetamu (Pax)',
        'live_total': 'Jumlah Terkini',
        'customize_order': 'Kustom & Tempah',
        'direct_add_cart': 'Terus Tambah Ke Troli',
        'no_packages_found_cat': 'Tiada pakej ditemui dalam kategori ini.',
        'back_to_menu': 'Kembali ke Menu',

        // Customizer
        'select_guest_count': 'Pilih Bilangan Tetamu (Pax)',
        'min_booking_requirement_is': 'Keperluan tempahan minimum adalah',
        'customize_extra_items': 'Kustom Barangan Tambahan',
        'addons_desc': 'Pilih hidangan tambahan untuk dimasukkan dalam set katering anda. Harga dinyatakan adalah untuk setiap pax.',
        'price_breakdown': 'Pecahan Harga',
        'base_pkg_price': 'Harga Pakej Asas',
        'guest_count': 'Bilangan Tetamu',
        'addon_extra': 'Tambahan Add-on',
        'combined_cost_pax': 'Kos Gabungan Per Pax',
        'grand_total': 'Jumlah Keseluruhan',
        'deposit_required': 'Deposit Diperlukan (30%)',
        'balance_due': 'Baki Perlu Dibayar (70%)',
        'selected_extra_items': 'Barangan Tambahan Dipilih',
        'add_to_cart': 'Tambah Ke Troli Beli-belah',
        'cancel': 'Batal',

        // Shopping Cart
        'package': 'Pakej',
        'price': 'Harga',
        'quantity': 'Bilangan',
        'subtotal': 'Subjumlah',
        'action': 'Tindakan',
        'order_summary': 'Ringkasan Pesanan',
        'selected_packages': 'Pakej Dipilih',
        'proceed_checkout': 'Teruskan ke Pembayaran',
        'continue_shopping': 'Teruskan Membeli-belah',
        'cart_empty': 'Troli beli-belah anda kosong',
        'cart_empty_desc': 'Anda belum memasukkan sebarang pakej katering ke dalam troli anda lagi.',
        'browse_packages_btn': 'Lihat Pakej',

        // Checkout
        'secure_checkout': 'Pembayaran Selamat',
        'event_delivery_details': 'Butiran Penghantaran Acara',
        'customer_name': 'Nama Pelanggan',
        'phone_number': 'No. Telefon',
        'delivery_event_date': 'Tarikh Penghantaran Majlis',
        'preferred_delivery_time': 'Masa Penghantaran Dipilih',
        'event_venue_address': 'Alamat Tempat Majlis',
        'payment_slip_deposit': 'Muat Naik Resit Pembayaran (30% Deposit)',
        'deposit_commitment_desc': 'Imbas kod QR di bawah atau pindahkan jumlah deposit 30% yang diperlukan ke akaun bank kami. Setelah pembayaran dibuat, sila muat naik gambar/PDF resit transaksi anda di bawah untuk mengesahkan tempahan tarikh majlis.',
        'scan_to_pay': 'Imbas untuk Bayar',
        'qr_not_configured': 'QR Belum Ditetapkan',
        'upload_payment_slip': 'Muat Naik Slip Pembayaran / Resit',
        'select_receipt_file': 'Pilih fail resit',
        'accepted_formats_desc': 'JPEG, PNG, PDF (Maksimum 4MB)',
        'confirm_booking_submit': 'Sahkan Tempahan & Hantar',

        // Bookings / Orders
        'my_bookings': 'Tempahan Saya',
        'all': 'Semua',
        'pending_rejected': 'Pending/Ditolak',
        'confirmed': 'Selesai Bayar Deposit',
        'delivered_tab': 'Dihantar',
        'awaiting_verification': 'Menunggu Pengesahan',
        'completed_tab': 'Selesai Majlis',
        'cancelled_tab': 'Dibatalkan',
        'order_id': 'ID Tempahan',
        'delivery_event_date_label': 'Tarikh Penghantaran Majlis',
        'total_price': 'Jumlah Harga',
        'status_label': 'Status',
        'order_timeline_tracker': 'Jejak Garis Masa Tempahan',
        'timeline_submitted': 'Dihantar',
        'timeline_confirmed': 'Deposit Disahkan (30%)',
        'timeline_delivered': 'Dihantar',
        'timeline_completed': 'Selesai Majlis (100%)',
        'rejection_reason_admin': 'Sebab Penolakan daripada Pentadbir:',
        'view_invoice': 'Lihat Invois',
        'reupload_receipt_btn': 'Muat Naik Semula Resit',
        'cancel_event_btn': 'Batal Majlis',
        'no_bookings_found': 'Tiada tempahan ditemui',
        'no_bookings_found_desc': 'Anda tidak mempunyai sebarang tempahan katering aktif atau lampau di bawah tapisan ini.',
        'pending': 'Pending',
        'deposit_rejected': 'Deposit Ditolak',
        'balance_rejected': 'Baki Ditolak',
        'confirm_cancel_order': 'Adakah anda pasti mahu membatalkan tempahan ini? Sila ambil perhatian bahawa deposit tidak akan dikembalikan.',
        'toast_order_cancelled': 'Tempahan berjaya dibatalkan.',
        'file_size_error': 'Saiz fail mestilah kurang daripada 4MB.',
        'toast_receipt_uploaded': 'Resit baru berjaya dimuat naik!',
        'uploading': 'Memuat naik...',

        // Invoice receipt Show
        'invoice_receipt': 'Invois & Resit',
        'print_invoice': 'Cetak Invois',
        'back_to_bookings': 'Kembali ke Tempahan',
        'billed_to': 'Dibilkan Kepada',
        'event_schedule_venue': 'Jadual & Tempat Acara:',
        'itemized_breakdown': 'Pecahan Barangan',
        'catering_service_package': 'Pakej Perkhidmatan Katering',
        'price_pax': 'Harga / pax',
        'guest_qty': 'Jumlah Tetamu',
        'payment_trans_status': 'Status Transaksi Pembayaran',
        'deposit_paid_invoice': 'Deposit Dibayar (30%)',
        'remaining_balance_invoice': 'Baki Perlu Dibayar (70%)',
        'thank_you_footer': 'Terima kasih kerana menempah dengan SmartServe Catering. Invois ini berfungsi sebagai bukti resit pendaftaran.',
        'issued': 'Dikeluarkan',
        'email': 'E-mel',
        'phone': 'Telefon',
        'setup_time': 'Masa Persediaan',
        'venue_address': 'Alamat Tempat Majlis',
        'base_cost': 'Kos Asas',
        'payment_desc_invoice': 'Deposit tempahan sebanyak 30% telah direkodkan. Baki sebanyak (70%) dijadualkan untuk dijelaskan pada atau sebelum tarikh penghantaran majlis.'
    }
};

export function useLocalization() {
    const t = (key) => {
        return translations[locale.value]?.[key] || translations['en']?.[key] || key;
    };

    const setLanguage = (lang) => {
        locale.value = lang;
        localStorage.setItem('ssc_locale', lang);
    };

    const currentLanguage = computed(() => locale.value);

    return {
        t,
        setLanguage,
        currentLanguage,
    };
}
